package com.tecnoplacita.machete.dto;



public enum RequestType {
    LEARNING_ASSISTANT,
    CONVERSATION_SIMULATION,
    EXERCISE_GENERATOR,
    TEXT_CORRECTION,
    PERSONAL_TUTORING,
    CODE_TRANSLATION,
    PROJECT_FEEDBACK,
    INFORMAL_CHAT,
    TECH_INTERVIEW_SIMULATION,
    PRONUNCIATION // Cambia PRONUNTIATION a PRONUNCIATION
}
